services:
  backend:
    build:
      context: "./"
      dockerfile: "./Dockerfile"
    ports:
      - "$SERVER_PORT:$SERVER_PORT"
    env_file:
      - "./.env"

  postgres:
    hostname: "postgres"
    image: "postgres:latest"
    expose:
      - "$POSTGRES_PORT"
    env_file:
      - "./.env"
